site_name: Les outils du logiciel libre pour l'ingénieur
docs_dir: ../md
repo_url: https://github.com/jeremyfix/OutilsLibres
site_url: https://jeremyfix.github.io/OutilsLibres
theme: 
  name: material
  language: fr
  features:
    - navigation.sections
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - ./js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:

site_url: https://jeremyfix.github.io/OutilsLibres

plugins:
    - mkdocs-video
    - search
    - glightbox

copyright: >
   <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://jeremyfix.github.io/OutilsLibres/">Outils du logiciel libre pour l'ingénieur</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://jeremyfix.github.io">Jeremy Fix</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p> 


nav:
  - Index: index.md
  - TP:
    - tps/bash.md
    - tps/makefile.md
    - tps/eruption.md
    - tps/meteo.md
  - Familiarisation avec le système Unix: 
    - outils/familiarisation.md
    - outils/gnu.md
  - Outils:
    - outils/help.md
    - outils/remote.md
    - outils/code.md
    - outils/correction.md
    - outils/autotask.md
    - outils/num.md
    - outils/images.md
    - outils/rapport.md
    - outils/vectoriel.md
    - outils/capture.md
    - outils/video.md
    - outils/pdf.md
    - outils/recherche.md
    - outils/filtrage.md
    - outils/compare.md
    - outils/archive.md
    - outils/interface.md
    - outils/web.md


